---
- name: Prepare DC
  hosts:
    - dc
  roles:
    - role: trippsc2.ad.testing_domain_controller
  tasks:
    - name: Create AD service account
      microsoft.ad.user:
        name: "{{ mssql_active_directory_user }}"
        password: "{{ mssql_active_directory_password }}"
        upn: "{{ mssql_active_directory_user }}@test.loc"
        attributes:
          set:
            msDS-SupportedEncryptionTypes: 24
        spn:
          set:
            - MSSQLSvc/linux
            - MSSQLSvc/linux.test.loc
            - MSSQLSvc/linux:1433
            - MSSQLSvc/linux.test.loc:1433
        state: present

    - name: Install SQL Server Management Studio
      chocolatey.chocolatey.win_chocolatey:
        name: sql-server-management-studio
        state: present

- name: Prepare member server
  hosts:
    - linux
  pre_tasks:
    - name: Create MSSQL group
      become: true
      ansible.builtin.group:
        name: mssql
        state: present
        system: true
    
    - name: Create MSSQL user
      become: true
      ansible.builtin.user:
        name: mssql
        group: mssql
        password: '!'
        password_lock: true
        state: present
        system: true
        shell: /usr/sbin/nologin
        home: /var/opt/mssql
        createhome: false
  roles:
    - role: trippsc2.ad.testing_linux_member
    - role: trippsc2.hashi_vault.testing_ca
    - role: trippsc2.hashi_vault.signed_certificate
      vars:
        cert_certificate_path: "{{ mssql_database_tls_certificate_path }}"
        cert_private_key_path: "{{ mssql_database_tls_private_key_path }}"
        cert_certificate_owner: mssql
        cert_certificate_group: mssql
        cert_private_key_owner: mssql
        cert_private_key_group: mssql
        cert_common_name: "{{ inventory_hostname }}"
        cert_subject_alternative_names:
          - "DNS:{{ inventory_hostname }}"
          - DNS:localhost
          - "IP:{{ ansible_host }}"
          - IP:127.0.0.1
        cert_copy_ca_chain: true
