---
- name: Modify AD user for SPN
  delegate_to: "{{ dc_inventory_name }}"
  microsoft.ad.user:
    name: vagrant
    upn: vagrant@test.loc
    attributes:
      set:
        msDS-SupportedEncryptionTypes: 24
    spn:
      add:
        - "MSSQLSvc/{{ inventory_hostname }}"
        - "MSSQLSvc/{{ inventory_hostname }}.test.loc"
        - "MSSQLSvc/{{ inventory_hostname }}:1433"
        - "MSSQLSvc/{{ inventory_hostname }}.test.loc:1433"
    state: present

- name: Import trippsc2.mssql.install role
  ansible.builtin.import_role:
    name: trippsc2.mssql.install

- name: Create vagrant domain user as admin
  when:
    - mssql_enable_active_directory_authentication | default(false)
  block:
    - name: Create vagrant domain user login
      delegate_to: localhost
      trippsc2.mssql.mssql_login:
        login_user: sa
        login_password: "{{ mssql_sa_password }}"
        login_host: "{{ ansible_host }}"
        login_port: 1433
        name: TEST\vagrant
        type: windows
        state: present
      retries: 3

    - name: Grant vagrant domain user CONTROL SERVER permissions
      delegate_to: localhost
      trippsc2.mssql.mssql_server_permission:
        login_user: sa
        login_password: "{{ mssql_sa_password }}"
        login_host: "{{ ansible_host }}"
        login_port: 1433
        principal: TEST\vagrant
        permissions:
          - control_server
        state: grant
