---
- name: Install
  ansible.builtin.include_tasks: win/install.yml

- name: Configure Windows Firewall
  when:
    - mssql_configure_firewall
  ansible.builtin.include_tasks: win/firewall.yml

- name: Configure
  ansible.builtin.include_tasks: win/configure.yml

- name: Configure monitoring
  when:
    - mssql_install_database_engine
    - mssql_configure_monitoring
  ansible.builtin.include_tasks: monitoring.yml

- name: Configure Vault database connection
  when:
    - mssql_install_database_engine
    - mssql_vault_configure_database_connection
  ansible.builtin.include_tasks: vault/connection.yml
