---
argument_specs:
  main:
    short_description: Microsoft SQL Server Install
    description:
      - This role installs Microsoft SQL Server.
    author:
      - Jim Tarpley
    options:
      dc_inventory_name:
        type: str
        required: false
        default: dc
        description:
          - The Ansible inventory name of the test domain controller.
