---
galaxy_info:
  author: Jim Tarpley
  namespace: trippsc2
  role_name: testing
  description: This role installs a testing Microsoft SQL Server.

  license: MIT

  min_ansible_version: '2.15'

  platforms:
    - name: EL
      versions:
        - '8'
        - '9'
    - name: Ubuntu
      versions:
        - focal
        - jammy

collections:
  - ansible.posix
  - ansible.windows
  - chocolatey.chocolatey
  - community.general
  - community.hashi_vault
  - community.windows
  - trippsc2.hashi_vault
  - trippsc2.windows

dependencies: []
