---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: dc
    box: jtarpley/w2022_cis
    memory: 2048
    cpus: 2
    groups:
      - windows
      - windows_domain
    provider_options:
      default_prefix: mssql_testing_
  - name: linux
    box: jtarpley/${MOLECULE_BOX:-rocky8_cis}
    memory: 4096
    cpus: 2
    groups:
      - subjects
    provider_options:
      default_prefix: mssql_testing_
provisioner:
  name: ansible
  inventory:
    group_vars:
      subjects:
        mssql_sa_password: SecurePassword123!
        mssql_enable_active_directory_authentication: true
      windows:
        ansible_shell_type: powershell
        ansible_become_method: runas
        ansible_become_user: SYSTEM
verifier:
  name: ansible
