---
- name: Validate distribution
  ansible.builtin.assert:
    that:
      - ansible_distribution in _mssql_supported_distributions
    fail_msg: "{{ ansible_distribution }} is not a supported distribution."
    success_msg: "Some releases of {{ ansible_distribution }} are supported.  Checking release."

- name: Include distribution variables
  ansible.builtin.include_vars: "{{ ansible_distribution }}/main.yml"

- name: Validate distribution release
  ansible.builtin.assert:
    that:
      - ansible_distribution_release in _mssql_supported_releases
    fail_msg: "{{ ansible_distribution }} {{ ansible_distribution_release }} is not a supported release."
    success_msg: "{{ ansible_distribution }} {{ ansible_distribution_release }} is supported."

- name: Include distribution release variables
  ansible.builtin.include_vars: "{{ ansible_distribution }}/{{ ansible_distribution_release }}.yml"

- name: Validate SQL Server version
  ansible.builtin.assert:
    that:
      - mssql_version | string in _mssql_supported_server_versions
    fail_msg: "SQL Server version {{ mssql_version }} is not supported on {{ ansible_distribution }} {{ ansible_distribution_release }}."
    success_msg: "SQL Server version {{ mssql_version }} is supported on {{ ansible_distribution }} {{ ansible_distribution_release }}."

- name: Validate Linux-specific variables
  ansible.builtin.include_tasks: validate/linux.yml
