---
_mssql_supported_server_versions:
  - '2017'
  - '2019'
  - '2022'

_mssql_prod_repo_url: https://packages.microsoft.com/rhel/8/prod/

_mssql_server_repo_url: >-
  https://packages.microsoft.com/rhel/8/mssql-server-{{ mssql_version }}/
