---
- name: Validate
  ansible.builtin.import_tasks: validate/main.yml

- name: Include Linux tasks
  when:
    - ansible_os_family != 'Windows'
  ansible.builtin.include_tasks: linux/main.yml

- name: Include Windows tasks
  when:
    - ansible_os_family == 'Windows'
  ansible.builtin.include_tasks: win/main.yml
